[tool.poetry]
name = "voiceforge"
version = "0.1.0"
description = ""
authors = ["Jean Carlo Corso"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
fastapi = "^0.110"
uvicorn = "^0.27"
python-multipart = "^0.0.9"
torch = ">=2.1,<2.2"
